"""One description per column of every published table. ci/kmeta.py attaches these to the Kaggle listing (the 'column description' score), reading the real
column order from each file and warning about any column that is missing here. (name, type, description); type is Kaggle's: string | numeric | boolean."""
S, N, B = "string", "numeric", "boolean"
SRC = ("source_url", S, "URL the document was published at (original or archived page URL).")
WB = ("wayback_url", S, "Internet Archive permalink of the exact capture the fact was read from. Empty for documents fetched from a live site.")

COLUMNS = {
    "crime_state_year.csv": [
        ("state_code", S, "ISO 3166-2:IN code of the state or union territory (MH, DL, KL ...); see ref_states.csv."),
        ("state", S, "State / UT name (current names; Orissa = Odisha etc.)."),
        ("year", N, "Calendar year the number refers to."),
        ("scope", S, "Which NCRB table family the number comes from: ipc, sll, women, children, scheduled_castes, scheduled_tribes, senior_citizens, juveniles, cyber. The same head appears in several families (rape under ipc and women), so keep scope in any filter."),
        ("crime_head", S, "Crime head exactly as the table prints it, parent heads first, joined by ' | ' (e.g. 'Murder (Sec.302 IPC) | A) Murder with Rape/POCSO')."),
        ("crime_category", S, "Canonical category of the head (see ref_categories.csv); all_crimes = a grand total, other = no rule matched. Inferred from the head text."),
        ("metric", S, "What the number counts: cases_registered, cases_chargesheeted, cases_convicted, persons_arrested, persons_chargesheeted, persons_convicted or victims."),
        ("value", N, "The number as published."),
        ("disputed", B, "True if another file reports a different value for the same state, year, scope, head and metric; the value shown is the one most tables agree on."),
        ("table_id", S, "NCRB's own table number (TABLE 3A.2 ...); empty for older files that carry none."),
        ("file", S, "Document id: join to documents.csv for the source URL, the Wayback permalink and the title. The original file is raw-<first character>/<file> in the crimebase-raw dataset."),
    ],
    "crime_india_year.csv": [
        ("year", N, "Calendar year the number refers to."),
        ("scope", S, "NCRB table family: ipc, sll, women, children, scheduled_castes, scheduled_tribes, senior_citizens, juveniles, cyber. Families overlap, so keep scope in any filter."),
        ("crime_head", S, "Crime head exactly as the table prints it, parent heads first, joined by ' | '."),
        ("crime_category", S, "Canonical category of the head (see ref_categories.csv); all_crimes = a grand total. Inferred from the head text."),
        ("metric", S, "cases_registered, cases_chargesheeted, cases_convicted, persons_arrested, persons_chargesheeted, persons_convicted, victims, rate (per lakh population, as published) or percentage (share of the table's total)."),
        ("value", N, "The number as published for all of India."),
        ("disputed", B, "True if another file reports a different value for the same year, scope, head and metric; the value shown is the one most tables agree on."),
        ("checked", B, "True if the number is the all-India row of a state table whose states add up to it (within 0.5%). National crime-head tables (2018 onward) have no state rows to check against."),
        ("table_id", S, "NCRB's own table number; empty for older files."),
        ("file", S, "Document id: join to documents.csv for the source URL and Wayback permalink."),
    ],
    "documents.csv": [
        ("file", S, "Document id (first 16 hex characters of its SHA-256 + extension). Same bytes under several URLs share one id."),
        ("raw_path", S, "Where the original file is in the crimebase-raw dataset (raw-<first character>/<file>)."),
        ("ext", S, "File type: pdf, xls, xlsx, csv, zip, doc, docx."),
        ("bytes", N, "File size in bytes."),
        ("publisher", S, "Organisation that published the document."),
        ("title_hint", S, "Readable guess at the title, from the file name in the URL."),
        ("year_hint", N, "Year named in the URL, when exactly one is; empty otherwise."),
        ("source_url", S, "First URL the file was seen at."),
        ("wayback_url", S, "Internet Archive permalink of the newest capture of these bytes; empty if only seen on a live site."),
        ("first_capture", S, "Date (YYYYMMDD) of the earliest Wayback capture."),
        ("last_capture", S, "Date (YYYYMMDD) of the latest Wayback capture."),
        ("n_urls", N, "Number of distinct URLs that served these bytes."),
        ("status", S, "facts = tables extracted to facts.parquet; facts_low_confidence = extracted from a PDF; no_tables_found = readable but no NCRB-style table; not_parsed = a type the parser does not read yet."),
        ("n_facts", N, "Number of numbers extracted from the file."),
    ],
    "facts.parquet": [
        ("file", S, "Document id; see documents.csv. The original is raw-<first character>/<file> in crimebase-raw."),
        SRC,
        ("sheet", S, "Sheet name inside the workbook ('pdf' for PDF extractions)."),
        ("table_id", S, "NCRB's own table number, when printed."),
        ("table_title", S, "Table title as printed above the header."),
        ("entity_type", S, "What the row is: state, district, city, crime_head, state_or_district or other."),
        ("entity", S, "Row label exactly as printed. Totals (is_total) are labelled e.g. 'TOTAL (ALL INDIA)'."),
        ("state_code", S, "ISO 3166-2:IN code when the row is a state / UT (or a city resolved to its state); empty otherwise."),
        ("parent_state_code", S, "For districts and cities: the state they belong to, when the table says so."),
        ("is_total", B, "True for total rows (all-India, state, grand total). Leave them out when summing."),
        ("column_label", S, "Full column header, header levels joined by ' | '. NCRB abbreviations (CR, CCS, PART ...) are kept as printed."),
        ("metric", S, "What the number counts (cases_registered, persons_arrested, ... rate, unknown). Inferred from the header text and NCRB's own abbreviations."),
        ("crime_category", S, "Canonical crime category (ref_categories.csv), judged from the crime head or header, leaf first. Inferred."),
        ("victim_group", S, "Who the table is about (women, children, senior_citizens, scheduled_castes, scheduled_tribes, foreigners, juvenile_offenders), from title or header; empty if not stated."),
        ("year", N, "Calendar year of the number; empty when the source only gives a range."),
        ("year_source", S, "Where the year was read from: row, column, sheet, title or path."),
        ("value", N, "The number as published (rates are per lakh population)."),
        ("format", S, "xls for Excel tables; pdf rows live in facts_pdf_lowconf.parquet."),
        ("wayback_timestamp", S, "14-digit capture time of the Wayback copy the fact was read from."),
        WB,
        ("publisher", S, "Organisation that published the document."),
        ("qc", S, "sum_ok / sum_mismatch / unchecked: do the state values add up (within 0.5%) to NCRB's own all-India row for that column and year?"),
        ("title_key", S, "Table title lower-cased with numbers removed: groups the same table across years."),
        ("n_sources", N, "How many files report a value for this exact key (entity, year, metric, column)."),
        ("conflict", B, "True if files disagree on the value for this key; all values are kept, none is silently overwritten."),
    ],
    "news.parquet": [
        ("url", S, "Article URL on the publisher's site (tracking parameters removed)."),
        ("domain", S, "Publisher's domain."),
        ("publisher", S, "Outlet name."),
        ("source_feed", S, "RSS feed the article was found in."),
        ("archived_snapshot", S, "For stories found in an archived copy of a feed: the Wayback permalink of that copy; empty for live reads."),
        ("published", S, "Publication date, YYYY-MM-DD."),
        ("category", S, "Crime category (ref_categories.csv)."),
        ("victim_group", S, "women, children, senior_citizens, scheduled_castes, scheduled_tribes, foreigners or juvenile_offenders; empty if not stated."),
        ("state_code", S, "ISO 3166-2:IN code of the state the story happened in, when it could be told; empty otherwise."),
        ("district", S, "District or city, matched against the places NCRB publishes."),
        ("stage", S, "Where the story sits in the criminal process: incident, arrest, investigation, trial, verdict. Filled only by the AI pass."),
        ("title", S, "Headline. Withheld (empty) for sexual-offence and child-victim stories."),
        ("summary", S, "The feed's own one-line summary, as syndicated by the publisher. Withheld with the headline."),
        ("sig", S, "Hashed headline words used to find duplicate reports."),
        ("labeller", S, "rules (keyword classifier) or llm (a language model also read the headline and judged it)."),
        ("cluster_id", S, "Reports of the same event share a cluster_id. Count distinct values for incidents."),
        ("archive_url", S, "Link that opens the newest Internet Archive capture of the article if one exists (otherwise the archive offers to save it)."),
    ],
    "news_events.parquet": [
        ("cluster_id", S, "Event id (same as news.parquet)."),
        ("first_published", S, "Date of the earliest report, YYYY-MM-DD."),
        ("last_published", S, "Date of the latest report."),
        ("category", S, "Most common category among the reports."),
        ("state_code", S, "Most common state among the reports."),
        ("district", S, "Most common district."),
        ("victim_group", S, "Most common victim group."),
        ("stage", S, "Furthest stage the coverage reached."),
        ("n_articles", N, "Reports of the event."),
        ("n_publishers", N, "Distinct outlets that reported it."),
        ("publishers", S, "Outlet names, comma-separated."),
        ("example_url", S, "URL of one report."),
    ],
    "ref_states.csv": [("state_code", S, "ISO 3166-2:IN code."), ("state", S, "State / UT name.")],
    "ref_categories.csv": [("category", S, "Category code used in crime_category / category."), ("description", S, "What it covers.")],
    "manifest.csv": [
        ("url", S, "URL the file was fetched from."),
        ("file", S, "Document id; the file is raw-<first character>/<file> in this dataset."),
        ("sha256", S, "SHA-256 of the file's bytes."),
        ("wayback_timestamp", S, "14-digit Internet Archive capture time; empty if fetched from a live site."),
        ("digest", S, "Internet Archive content digest of the capture."),
        ("publisher", S, "Organisation that published the document."),
        ("retrieved", S, "Date fetched from a live site (empty for Wayback captures)."),
    ],
}
COLUMNS["facts_pdf_lowconf.parquet"] = COLUMNS["facts_raw.parquet"] = COLUMNS["facts.parquet"]  # same columns (facts_raw: a subset)
